  function showPoem(param) {
    // Get the lightbox overlay and content elements
    var lightboxOverlay = document.getElementById('lightbox-overlay');
    var lightboxContent = document.getElementById('lightbox-content');

    // Set the text based on the parameter
    lightboxContent.innerHTML = getHaikuForElement(param) + "<p/>";

    // Display the lightbox
    lightboxOverlay.style.display = 'flex';
  }

  function closePoem() {
    // Hide the lightbox
    document.getElementById('lightbox-overlay').style.display = 'none';
  }

  function getHaikuForElement(elementNum) 
        {
          const haiku = [];
          haiku[0] = "";
          haiku[1] = "<b>1 Hydrogen</b><br/><br/>two-thirds of water<br>a big part of all of us<br>and the bones of stars<br/><br/><br/>&nbsp;&nbsp;&nbsp;<a href='mailto:davidkm@gsa.state.al.us'>David C. Kopaska-Merkel</a>&nbsp;<p/>";
          haiku[2] = "<b>2 Helium</b><br/><br/>lighter than dream<br/>flight between worlds<br/><br/>Deja Thoris<br/>serial rescues in<br/>afternoon sun<br/><br/>&nbsp;&nbsp;&nbsp;<a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a>&nbsp;&copy;2001<p>";
          haiku[3] = "<b>3 Lithium</b><br/><br/>battery charge<br/>- and great to slice!<br/><br/>&nbsp;&nbsp;&nbsp;<a href='mailto:stavrogin@tiscalinet.it'>Stavrogin</a>&nbsp;<p>";
          haiku[4] = "<b>4 Beryllium</b><br/><br/>stable conductor<br/>detecting radiation<br/>reflecting neutrons<br/><br/>&nbsp;&nbsp;&nbsp;<a href='mailto:viki@pacbell.net'>viki</a>&nbsp;<p>";
          haiku[5] = "<b>5 Boron</b><br/><br/>Brown propellant gives<br/>roadside help, but abrasive<br/>rubs us the wrong way<br/><br/>&nbsp;&nbsp;&nbsp;<a href='mailto:karenr2@mediaone.net'>Karen A. Romanko</a>&nbsp;<p>";
          haiku[6] = "<b>6 Carbon</b><br/><br/>Dead stars reborn<br/>as diamonds, buckeyballs,<br/>and beings<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;<a href='mailto:shal@loc.gov'>Stephanie Hall</a>";
          haiku[7] = "<b>7 Nitrogen</b><br/><br/>the sky's referee,<br/>without its calming effect,<br/>oxygen will burn<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;<a href='mailto:scv@scvs.com'>s.c. virtes</a>";
          haiku[8] = "<b>8 Oxygen</b><br/><br/>Green plants' waste;<br/>Earth's invisible treasure:<br/>now breathe.<br/><br/><a href='mailto:shal@loc.gov'>Stephanie Hall</a>";
          haiku[9] = "<b>9 Fluorine</b><br/><br/>science is risky<br/>so hard to get it alone<br/>but find it and die<br/><br/>&nbsp;&nbsp;<a href='mailto:davidkm@gsa.state.al.us'>David C. Kopaska-Merkel</a>&nbsp;<p/>";
          haiku[10] = "<b>10 Neon</b><p/>buzzing florescence ...<br/>asteroid miners weave<br/>  out the cavern door<br/><br/>    gK &copy; 2001.01.27";
          haiku[11] = "<b>11 Sodium</b><p/>A spring snow<br/>Upon my edged tongue<br/>I smile<br/><br/><a href='mailto:eggsalad@mail.com'>Jonathan Lee</a>";
          haiku[12] = "<b>12 Magnesium</b><p/>Magnesium flares<br/>Silvery-white<br/>When called quicklime<p/><a href='mailto:sdr633@hotmail.com'>Stephen D. Rogers</a>";
          haiku[13] = "<b>13 Aluminum</b><p/>helps in the kitchen<br/>we don't find it everywhere<br/>makes us forget stuff<p/><a href='mailto:davidkm@gsa.state.al.us'>David C. Kopaska-Merkel</a>";
          haiku[14] = "<b>14 Silicon</b><p/>silicon enhanced . . .<br/>mind-meld with my computer<br/>our modems exchange<p/><a href='mailto:gradidge@mb.sympatico.ca'>ushi </a>";
          haiku[15] = "<b>15 Phosphorus</b><p/>steeped in water and<br/>mystery -- until exposed<br/>white phosphorus glare<p/><a href='mailto:scv@scvs.com'>s.c. virtes</a>";
          haiku[16] = "<b>16 Sulfur</b><p/>Pharmaceuticals'<br/>friend in antibiotics<br/>makes me allergic<p/><a href='mailto:karenr2@mediaone.net'>Karen A. Romanko</a>";
          haiku[17] = "<b>17 Chlorine</b><p/>sea-change<br/>from salt of the earth<p/>mustard<br/>frieze of global fire<p/>twofold<br/>fresh water colours<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy;2001";
          haiku[18] = "<b>18 Argon</b><p/>Trapped inside glass tubes<br/>glowing filaments slumber--<br/>idle argon waits.<p/><a href='mailto:Arion214@aol.com'>Pam Smith</a>";
          haiku[19] = "<b>19 Potassium</b><p/>The laughing chemist,<br/>tasting the salts of the earth:<br/>ashes, ashes.<p/><div style='font-size:0.8em'><i>[Sir Humphry Davy is best remembered as the chemist who investigated the properties of nitrous oxide ('laughing gas') and its effects, by experimenting on himself. He entertained friends at parties by providing the gas to inhale. He also discovered several elements as an early experimenter with electrolysis, beginning with potassium and sodium in 1807. Since poets, including Coleridge, were among those in Davy's circle, I can't help but think he would have enjoyed the idea of celebrating the elements with poetry. The name for potassium is derived from 'potash' from which it was isolated.]</i><p/><a href='https://web.archive.org/web/20041227031445/mailto:shal@loc.gov'>Stephanie Hall</a></div>";
          haiku[20] = "<b>20 Calcium</b><div align='left'>Festering cows<br/>puss and antibiotics<br/>&nbsp;got milk, kids?<p/><a href='mailto:ron@ron.sparks+ptoe@gmail.com'>Ron Sparks</a> &copy; 02/04/01</div>";
          haiku[21] = "<b>21 Scandium</b><p/>snow white Norse powder<br/>getting there was half the fun-<br/>makes you stronger, Al<p/><i>[Makes Aluminum stronger- the Russians used it in their MiG fighters]</i><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[22] = "<b>22 Titanium</b><p/>this skin<br/>glistening hardness-<br/>titanium<p/><a href='mailto:lucien2@juno.com'>lucien</a>";
          haiku[23] = "<b>23 Vanadium</b><p/>vanadium oxide peeps<br/>through surface from cool star's deep<br/>convective mixing.<p/><a href='mailto:dianeturnshek@home.com'>Starlady </a>";
          haiku[24] = "<b>24 Chromium</b><p/>nose ring shine<br/>the cyberpunk smiles-<br/>chromium<p/><a href='mailto:lucien2@juno.com'>lucien</a>";
          haiku[25] = "<b>25 Manganese</b><p/>strong bones<br/>in humans<br/>and steel<p/><div style='font-size:0.8em'><i>Manganese is needed for healthy skin, bone, and cartilage formation, as well as glucose tolerance. It also helps activate superoxide dismutase (SOD)-an important antioxidant enzyme. (from <a href='http://www.mothernature.com/ency/Supp/Manganese.asp'>here</a>)<p/>Manganese is essential to iron and steel production by virtue of its sulfur-fixing, deoxidizing, and alloying properties. Steelmaking, including its ironmaking component, accounts for most domestic manganese demand, presently in the range of 85% to 90% of the total. (from <a href='http://minerals.usgs.gov/minerals/pubs/commodity/manganese/'>here</a>)</i></div><a href='https://web.archive.org/web/20041225043201/mailto:Mark.Dowdey@wcom.com'>Mark Dowdey</a>";
          haiku[26] = "<b>26 Iron</b><p/>prehistoric gift<br/>splashing history currents<br/>  leaving flakes of rust<p/><a href='mailto:dkolodji@aol.com'>Deborah P. Kolodji</a>";
          haiku[27] = "<b>27 Cobalt</b><p/>sky fallen goblin --<br/>fierce eyes flash cobalt blue<br/>on runic dagger<p/><div style='font-size:0.8em'><i>[Cobalt comes from the German word 'Kobold' meaning 'goblin' or evilspirit. Brittle but hard cobalt is found in meteorites and has magnetic properties of iron.]</i></div><p/><a href='mailto:gradidge@mb.sympatico.ca'>ushi</a>";
          haiku[28] = "<b>28 Nickel</b><p/>under the granite<br/>of the Canadian Shield-<br/>deep nickel shines<p/><div style='font-size:0.8em'><i>( Nickel-a hard silvery-white metal found in igneous rocks and meteorites. From Swedish nikel, which means devil )</i></div><p/><a href='mailto:lucien2@juno.com'>lucien</a>";
          haiku[29] = "<b>29 Copper</b><p/>on my backbone<br/>songs of civilization-<br/>copper<p/><a href='mailto:lucien2@juno.com'>lucien</a>";
          haiku[30] = "<b>30 Zinc</b><p/>galvanized iron,<br/>cosmetics, preservatives,<br/>a salt, and batteries.<p/><a href='mailto:ksmsg02@tamuk.edu'>Mike</a>";
          haiku[31] = "<b>31 Gallium</b><p/>generic metal<br/>until prodded, excited<br/>melting in your hand<p/><a href='mailto:scv@scvs.com'>s.c. virtes</a>";
          haiku[32] = "<b>32 Germanium</b><p/>organogermanium<br/>chemotherapy agent -<br/>the quiet bacteria<p/><a href='mailto:toddtwo@prodigy.net'>robert leechford</a> &copy;2001";
          haiku[33] = "<b>33 Arsenic</b><p/>still welling up, stiff-necked<br/>beside the old claim; morning glass<br/>of arsenic, straight laced<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy;2001";
          haiku[34] = "<b>34 Selenium</b><p/>in quiet moonlight<br/>a tiny breath is felt-<br/>selenium<p/><div style='font-size:0.8em'><i>( Selenium- a nonmetallic element used in photoelectric cells. From Greek selene-which means moon. )</i></div><p/><a href='mailto:lucien2@juno.com'>lucien</a>";
          haiku[35] = "<b>35 Bromine</b><p/>This fuming, toxic liquid<br/>dark red, stinking, fetid:<br/>Satan's favorite brew.<p/><a href='mailto:Arion214@aol.com'>PamSmith</a>";
          haiku[36] = "<b>36 Krypton</b><p/>so vulnerable --<br/>this frail tube connecting<br/>points of steel<p/><div style='font-size:0.8em'><i>[used with argon as a low-pressure filling gas for fluorescent lights]</i></div><p/><a href='https://web.archive.org/web/20050114004342/mailto:gradidge@mb.sympatico.ca'>ushi</a>";
          haiku[37] = "<b>37 Rubidium</b><p/>magnetohydrodynamic -<br/>rubidium ions<br/>brushing the magnets<p/><a href='mailto:toddtwo@prodigy.net'>robert leechford</a> &copy;2001";
          haiku[38] = "<b>38 Strontium</b><div align='left'>incognito<br/>in calcium’s demesne<br/>&nbsp;radiated bones<br/><br/><a href='mailto:ron@ron.sparks+ptoe@gmail.com'>Ron Sparks</a> &copy; 02/04/01</div>";
          haiku[39] = "<b>39 Yttrium</b><p/>small amulet<br/>buried in niche of time:<br/>laser garnet<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 02/04/01";
          haiku[40] = "<b>40 Zirconium</b><p/>has the distinction<br/>of making crystals so tough<br/>they're older than rocks<p/><a href='mailto:davidkm@gsa.state.al.us'>David C. Kopaska-Merkel</a>";
          haiku[41] = "<b>21 Scandium</b><p/>all in tears<br/>proud labors lost<br/>sun's nova<p/><i>[Queen Niobe of Thebes boasted of her many sons and daughters. They were struck down by the god Apollo, leaving her nothing but tears.]</i><p/><a href='mailto:blucinda@usa.net'>lucindab</a>";
          haiku[42] = "<b>42 Molybdenum</b><p/>what is it good for?<br/>making great steel, future stuff-<br/>fine, Tov, but what is steel?<p/><i>[guess you have to wait for the future]</i><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[43] = "<b>43 Technetium</b><p/>beyond the man-made<br/>a marker in bright depths of<br/>overactive stars<p/><a href='mailto:scv@scvs.com'>s.c. virtes</a>";
          haiku[44] = "<b>44 Ruthenium</b><p/>forged weapons<br/>ruthenium alloys<br/>mighty pens<p/><i>[ruthenium is used with other materials to make electrical contacts and pen tips]</i><p/><a href='mailto:IrulanAtreides@webtv.net'>-SAKYU-</a>";
          haiku[45] = "<b>45 Rhodium</b><p/>Thousand Dollar Ounce<br/>precious metal catalyst<br/>wedding bed fusion.<p/><div style='font-size:0.8em'><i>[Rhodium's primary use is as an alloying agent to harden platinum, and is also used for jewelry, for decoration, and as a catalyst.]</div><p/><a href='mailto:viki@pacbell.net'>viki</a> &copy;0102.12";
          haiku[46] = "<b>46 Palladium</b><p/>white<br/>gold<br/>vining<br/>his muddy<br/>buckler; rapier<br/>tracery across his cheekbones;<br/>geas still centuries-fresh: palladium avatar<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[47] = "<b>47 Silver</b><p/>silver pentagram<br/>hung above a yeoman's berth<br/>superstitious crew<p/><a href='mailto:IrulanAtreides@webtv.net'>-SAKYU-</a>";
          haiku[48] = "<b>48 Cadmium</b><p/>child babbles nonsense<br/>burned-out plastic brain gears<br/>too much cadmium<p/><div style='font-size:0.8em'><i>[Fact: cadmium toxicity causes Learning Disabilities, affecting verbal skills. Exposure to tobacco, auto exhaust, zinc smelters, fertilizers, galvanized water pipes, and burning plastics can cause high enough levels for LD.]</i></div><p/><a href='mailto:/'>lil* &copy; 1-28-01</a>";
          haiku[49] = "<b>49 Indium</b><p/>O mirror mirror<br/>a surface of indium<br/>farest one of all<p/><a href='mailto:misselise@purplepens.com'>E. Catherine Tobler</a>";
          haiku[50] = "<b>50 Tin</b><p/>the pan pipes<br/>ancient elemental cry --<br/>hearts broken<p/><a href='mailto:gradidge@mb.sympatico.ca'>ushi</a>";
          haiku[51] = "<b>51 Antimony</b><p/>Newton's alchemy --<br/>crystal starred in his sights<br/>regulus of Mars<p/><div style='font-size:0.8em'><i>The term 'starred' was here employed by Newton in its most literal sense. For if the antimony has been properly purified as in this instance, it forms long and slender crystals. During cooling the crystals in turn form triangular branches around a central point, taking on the aspect of a silver star. Masters of the symbolic, the alchemists named this heart of antimony ore after Regulus, the bright double star near the heart of the constellation Leo. When the star regulus of antimony was achieved with the aid of a metallic reducing agent in the above experiment, Newton had produced the star regulus of Mars.</i></div><p/><a href='mailto:gradidge@mb.sympatico.ca'>jane-a</a>";
          haiku[52] = "<b>52 Tellurium</b><p/>steel<br/>framed<br/>alloy<br/>mirror shades<br/>impatient for the<br/>sunset; decadent umlauts mark<br/>the bloodlines...everything old so-what new forever<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[53] = "<b>53 Iodine</b><p/>Fearful brown bottle!<br/>Its sting presages a scar --<br/>a new lesson learned.<p/><a href='mailto:laurenwl@yahoo.com'>Lauren</a>";
          haiku[54] = "<b>54 Xenon</b><p/>o noble gas -<br/>what thou dost<br/>with 6 Flourines!?<p/><a href='mailto:stavrogin@tiscalinet.it'>Stavrogin</a>";
          haiku[55] = "<b>55 Cesium</b><p/>parallel blues -- metronomic fire --  caesium kiss<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[56] = "<b>56 Barium</b><p/>the bitter cocktail<br/>of a colonoscopy --<br/>grin and barium<p/><a href='mailto:scv@scvs.com'>s.c. virtes</a>";
          haiku[57] = "<b>57 Lanthanum</b><p/>Hollywood cool<br/>flash focus reactive:<br/>L-Anthanum<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[58] = "<b>58 Cerium</b><p/>Lighter flints contain<br/>this metal, which often sparked<br/>post-coital prattle.<p/><a href='mailto:kadaniels1@earthlink.net'>Keith Allen Daniels</a> &copy; 2001";
          haiku[59] = "<b>59 Praseodymium</b><p/>praise, O dymium<br/>glassblowers honor thy name-<br/>glasses to make glass<p/><div style='font-size:0.8em'><i>[Rumored to be a pal of the Greek god, Neodymium. Those cool dark glasses that welders use? Neodymium- how did you know?]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[60] = "<b>60 Neodymium</b><p/>oh, pretty colors<br/>welders goggles' colored glass-<br/>lasers, enamels<p/><div style='font-size:0.8em'><i>[More glass coloring, but beautiful delicate shades. Glass for spectral line calibration. Would wine glasses be too much to ask?]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[61] = "<b>61 Promethium</b><p/>handful of pain<br/>blue against eagle nights:<br/>promethium<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[62] = "<b>62 Samarium</b><p/>tiny cracks appear<br/>the beginning of the end-<br/>samarium<p/><div style='font-size:0.8em'><i>( Samarium is a hard, brittle, grayish white rare-earth metal used in control rods in nuclear reactors. )</i></div><p/><a href='mailto:lucien2@juno.com'>lucien</a>";
          haiku[63] = "<b>63 Europium</b><p/>red TV phosphors<br/>as seen in the sun and stars-<br/>its future is bright<p/><div style='font-size:0.8em'><i>[The most reactive of the rare-earth metals. Used for the red color TV phosphor, laser material. Good neutron absorber- and you know what that means... nuclear reactor control rods. About $213 an ounce- if you were wanting some.]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[64] = "<b>64 Gadolinium</b><p/>gadolinium -<br/>ferromagnetic atoms rotate<br/>one after another<p/><a href='mailto:toddtwo@prodigy.net'>robert leechford</a> &copy; 2001";
          haiku[65] = "<b>65 Terbium</b><p/>xenotime<br/>glitters underfoot<p/><div style='font-size:0.8em'><i>eminence grise<br/>laser edged</i></div><p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[66] = "<b>66 Dysprosium</b><p/>playing hard to get<br/>half dead in 3 million years-<br/>can't see your color.<p/><div style='font-size:0.8em'><i>[One of the most magnetizable substances. Used in mercury vapor lamps to get brighter and better color balanced light. Yeah.]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[67] = "<b>67 Holmium</b><p/>more silver bullets<br/>lasers to blast kidney stones-<br/>sucking up neutrons.<p/><div style='font-size:0.8em'><i>[Holmia, for Stockholm. Another element used for making nuclear reactor control rods, Holmium absorbs neutrons readily. The kidney stone blaster is a personal reference- a kidney stone nearly took me out. My surgeon crushed it the old way, I think with a logger's boot.  Ten bucks a gram. Cheap, I'd say.]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[68] = "<b>68 Erbium</b><p/>lovely pastel pink<br/>makes vanadium harder-<br/>color for glazes.<p/><div style='font-size:0.8em'><i>[Erbium is used in nuclear and metallurgical applications, and as a colorant for glasses and porcelain glazes.]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>Loyd Myatt</a>";
          haiku[69] = "<b>69 Thulium</b><p/>green, with oxygen,<br/>O, Ultima Thulium,<br/>you see through my flesh.<p/><a href='mailto:73143.3376@compuserve.com'>Timons Esaias</a>";
          haiku[70] = "<b>70 Ytterbium</b><p/>made of cast Ytterbium<br/>alien mummy's scarab<p/><a href='mailto:blucinda@usa.net'>lucindab</a>";
          haiku[71] = "<b>71 Lutetium</b><p/>a job for Lulu<br/>test meteorite ages-<br/>no more work, sorry<p/><div style='font-size:0.8em'><i>[It seems so sad for the densest and hardest rare earth element]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[72] = "<b>72 Hafnium</b><p/>I'm in solid, Zirc<br/>make nuclear control rods-<br/>I can take the heat<p/><div style='font-size:0.8em'><i>[named for Copenhagen- Hafnia]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[73] = "<b>73 Tantalum</b><p/>ductile web<br/>surgically lensed:<br/>tantalum<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[74] = "<b>74 Tungsten</b><p/>night's darkness<br/>pierced by the light-<br/>tungsten<p/><a href='mailto:lucien2@juno.com'>lucien</a>";
          haiku[75] = "<b>75 Rhenium</b><p/>superconductive<br/>Re-Mo alloys at 10K-<br/>a working metal.<p/><div style='font-size:0.8em'><i>[Very ductile metal. Rhenium-molybdenum alloys are superconductive at 10 degrees Kelvin. Used to make mass spectrograph filaments and ion gauges, and wire for photoflash lamps. And it's swell electrical contact material because it has good wear and corrosion resistance.]</i></div><p/><a href='mailto:gradidge@mb.sympatico.ca'>Loyd Myatt</a>";
          haiku[76] = "<b>76 Osmium</b><p/>Glowing density --<br/>Brighten my yellow brick road...<br/>lead me home.<p/><a href='mailto:Arion214@aol.com'>PamSmith</a>";
          haiku[77] = "<b>77 Iridium</b><p/>brittle alloy<br/>corroded by salt<br/>one hot pot<p/><a href='mailto:viki@pacbell.net'>viki</a>";
          haiku[78] = "<b>78 Platinum</b><p/>fresh vein opened<br/>extracting precious lode<br/>conversion sequence active<p/><p>one-of-six in display mode<br/>system overload</i></p><p/><a href='mailto:tlrelf@pacbell.net'>semi</a>";
          haiku[79] = "<b>79 Gold</b><p/>Alchemy itself,<br/>transmuter of history:<br/>panning for dreams.<p/><a href='mailto:shal@loc.gov'>Stephanie Hall</a>";
          haiku[80] = "<b>80 Mercury</b><p/>Liquid silver flows<br/>like Hermes wings and shield made<br/>molten by the sun.<p/><a href='mailto:Arion214@aol.com'>PamSmith</a>";
          haiku[81] = "<b>81 Thallium</b><p/>O virulent rat,<br/>vile bringer of death, beware<br/>of Thallium's sheen<p/><a href='mailto:sxjames@hotmail.com'>Shawn James</a>";
          haiku[82] = "<b>82 Lead</b><p/>plumbing its decadence -- civilization<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[83] = "<b>83 Bismuth</b><p/>fusible alloys<br/>& super magnets - queasy?<br/>pepto might just help<p/><a href='scv@scvs.com'>s.c. virtes</a>";
          haiku[84] = "<b>84 Polonium</b><p/>my native land<br/>conquered for so long --<br/>this bit freed first<p/><div style='font-size:0.8em'><i>[Marie Curie named the first element she found in pitchblende ore after her native country, Poland, then mostly under Tsarist Russian control]</i></div><p/><a href='mailto:blucinda@usa.net'>lucindab</a>";
          haiku[85] = "<b>85 Astatine</b><p/>Unnatural. Rare.<br/>Unstable, unknown, man-made,<br/>Short half-life; it fades.<p/><a href='mailto:amamhaye@indiana.edu'>Amanda M. Hayes</a>";
          haiku[86] = "<b>86 Radon</b><p/>from the stars<br/>we feed on radon:<br/>basement ghosts<p/><a href='mailto:Kelly_Patricia@email.msn.com'>Patricia Kelly</a>";
          haiku[87] = "<b>87 Francium</b><p/>twenty tenses,<br/>plus perfect isotopic<br/><br/>twenty-two minutes,<br/>pre-Vichy naturally<p/><div style='font-size:0.8em'><i>(Le Francais only has seventeen tenses, please forgive a bit of poetic license)</i></div><p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[88] = "<b>88 Radium</b><p/>Strongest medicine:<br/>Marie's little beaker<br/>of life and death.<p/><a href='mailto:shal@loc.gov'>Stephanie Hall</a>";
          haiku[89] = "<b>89 Actinium</b><p/>nuclear power<br/>dark afterglow shimmers<br/>reactor life span<p/><a href='mailto:viki@pacbell.net'>viki</a>";
          haiku[90] = "<b>90 Thorium</b><p/>sound of thunder<br/>from the old god's forge-<br/>thorium<p/><div style='font-size:0.8em'><i>( Thorium- a dark grey, radioactive,metal. When Thorium is bombarded with neutrons, it changes into uranium 233. From Swedish Thor, the Scandinavian god of thunder )</i></div><p/><div style='font-size:0.8em'><i>( this one's for you, Ulf )</i></div><p/><a href='mailto:lucien2@juno.com'>lucien</a>";
          haiku[91] = "<b>91 Protactinium</b><p/>you can't be no good<br/>mother of actinium-<br/>thanks to your decay<p/><div style='font-size:0.8em'><i>[first it was called Protoactinium, then Protactinium- now I see Proactinium. I'm waiting for Protium and Prozac]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[92] = "<b>92 Uranium</b><p/>Fission or fusion?<br/>World leaders seek security<br/>As uranium time ticks away<p/><a href='mailto:bobmerkel@earthlink.net'>Bob Merkel</a>";
          haiku[93] = "<b>93 Neptunium</b><p/>All aboard!<br/>Transuranium Express<br/>bound for the unknown.<p/><a href='mailto:shal@loc.gov'>Stephanie Hall</a>";
          haiku[94] = "<b>94 Plutonium</b><p/>burial markers<br/>destroyed by vandals<p/><p>unEarthing<br/>future plague<br/></p><p>legacy of death<br/>no prophet warnings</p><p/><a href='mailto:lucien2@juno.com'>lucien</a>";
          haiku[95] = "<b>95 Americium</b><p/>Fire's high-tech bane,<br/>radiation's toxic pain--<br/>Americium Dream<p/><a href='mailto:sxjames@hotmail.com'>Shawn James</a>";
          haiku[96] = "<b>96 Curium</b><p/>all the way to Mars<br/>before one human footstep<br/>curium spectrometer<p/><a href='mailto:IrulanAtreides@webtv.net'>(xeno-unit)</a>";
          haiku[97] = "<b>97 Berkelium</b><p/>just academic<br/>protesting commercial use<br/>feels it in his bones<p/><a href='mailto:dkolodji@aol.com'>Deborah P. Kolodji</a>";
          haiku[98] = "<b>98 Californium</b><p/>emitting neutrons<br/>man-made & temperamental<br/>exploding star dreams<p/><div style='font-size:0.8em'><i>(A synthetic element that some suggest may be produced in supernovae, although this theory is questioned.)</i></div><p/><a href='mailto:dkolodji@aol.com'>Deborah P. Kolodji</a>";
          haiku[99] = "<b>99 Einsteinium</b><p/>laughing with God<br/>eternal craps game<br/>betting GUTs<p/><div style='font-size:0.8em'><i>['If you want to give God a laugh, tell him your plans']<br/>['God does not play at dice with the Universe']<br/>[Grand Unified Theory, a mystery he planned to solve]</i></div><p/><a href='mailto:oinosakai@mad.scientist.com'>oino sakai</a>";
          haiku[100] = "<b>100 Fermium</b><p/>deadly debris<br/>neutron irradiation<br/>half-life residue<p/><a href='mailto:viki@pacbell.net'>viki</a> &copy; 0102.12";
          haiku[101] = "<b>101 Mendelevium</b><p/>almost forgotten<br/>my Table lives after me<br/>a lesson on pride<p/><div style='font-size:0.8em'><i>[The value of Mendeleev's table is that it predicted the gaps in the vertical rows, indicated the properties of the then-missing elements and suggested where to look for them in Nature. But all other knowledge of Mendeleev himself was nearly lost to time and indifference.]</i></div><p/><a href='mailto:blucinda@usa.net'>lucindab</a>";
          haiku[102] = "<b>102 Nobelium</b><p/>predicting the spin --<br/>nobelium football coach<br/>non-magic talent<p/><div style='font-size:0.8em'><i>[Heavy element nobelium - 'nonmagic' stability seems to be a deformation of the nucleus into a football shape.]</i></div><p/><a href='mailto:gradidge@mb.sympatico.ca'>jane-a</a>";
          haiku[103] = "<b>103 Lawrencium</b><p/>cyclotron spirals<br/>accelerating his name<br/>a rare earth metal<p/><a href='mailto:dkolodji@aol.com'>Deborah P. Kolodji</a>";
          haiku[104] = "<b>104 Rutherfordium</b><p/>old discoverer:<br/>'The atom will never split!'<br/>Rutherfordium<p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[105] = "<b>105 Dubnium</b><p/>the doors<br/>into post-perfect<br/>Liffey bridge-fading<br/>Dubnium<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[106] = "<b>106 Seaborgium</b><p/>just a second !<br/>Seaborg and his cyclotron<br/>brand new elements<p/><div style='font-size:0.8em'><i>[Seaborgium has a half-life of less than a second. 'Discovery of plutonium ... took place in 1940, when Seaborg, McMillan, Joseph Kennedy, and Arthur Wahl, using the 60-inch cyclotron built by Ernest Lawrence, bombarded a sample of uranium with deuterons and transmuted it into plutonium. Seaborg and his co-workers used the discovery of plutonium as a stepping stone to the creation of a succession of transuranium elements--americium, curium, berkelium, californium, einsteinium, fermium, mendelevium, nobelium, and ... seaborgium.']</i></div><p/><a href='mailto:gradidge@mb.sympatico.ca'>jane-a</a>";
          haiku[107] = "<b>107 Bohrium</b><p/>synthesis<br/>of metallic nows<br/>pinpoint dance<br/>on fugitive lives<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[108] = "<b>108 Hassium</b><p/>half<br/>life<br/>silver<br/>walkabout;<br/>kireji ahas<br/>balance on a finger outstretched<br/>through noh spacetime.. . .finality scatters in bone dust<p/><a href='mailto:MMSerpento@aol.com'>Mary Margaret Serpento</a> &copy; 2001";
          haiku[109] = "<b>109 Meitnerium</b><p/>after a day's work<br/>make us something we can use-<br/>well, it's magnetic.<p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[110] = "<b>110 Ununnilium</b><p/>the next big challenge:<br/>a fleeting glimpse, a breakdown,<br/>faint detector flash!<p/><a href='mailto:scv@scvs.com'>s.c. virtes</a>";
          haiku[111] = "<b>111 Unununium</b><p/>Shake and shout,<br/>'Unununium! The new<br/>reality rag!'<p/><a href='mailto:shal@loc.gov'>Stephanie Hall</a>";
          haiku[112] = "<b>112 Ununbium</b><p/>shooting in the dark<br/>come on out with your Hans up-<br/>our work goes so fast.<p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[113] = "<b>113 Ununtrium</b><p/>incomplete study<br/>filling a place at tables --<br/>the waitressing stage<p/><a href='mailto:gradidge@mb.sympatico.ca'>jane-a</a>";
          haiku[114] = "<b>114 Ununquadium</b><p/>one one four<br/>transient in the rain<br/>disconnected Borg<p/><div style='font-size:0.8em'><i>[No name has yet been suggested for element 114, which is therefore called ununquadium, from the Latin roots un for one and quad for four, under a convention for neutral temporary names proposed by the International Union of Pure and Applied Chemistry (IUPAC) in 1980.]</i></div><p/><a href='mailto:gradidge@mb.sympatico.ca'>ushi</a>";
          haiku[115] = "<b>115 Ununpentium</b><p/>what? reactor fuel?<br/>antigravity engine?<br/>here come the wackos<p/><div style='font-size:0.8em'><i>[Wierdness abounds: on one site it says, 'The reactor found in the alien craft at S4, as widely mentioned by physicist Robert Lazar is primarily based on a superheavy element with atomic number 115.' Oh dear. How 'bout another nice silver metal you can use for nuclear reactor rods?)]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[116] = "<b>116 Ununhexium</b><p/>Uuh... wham bam daughter<br/>two trillion krypton atoms-<br/>what do you expect?<p/><div style='font-size:0.8em'><i>[The immediate decay product of element 118 as it works its way on down to 104.]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[117] = "<b>117 Ununseptium</b><p/>F117<br/>flying under our radar-<br/>nighthawk stealth atom<p/><div style='font-size:0.8em'><i>[The coincidence is too sweet with the F117 Nighthawk aircraft used in Desert Storm to miss. Expected to be solid at 298K. Unknown color because it hasn't been discovered yet. Maybe it will be midnight blue.]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";
          haiku[118] = "<b>118 Ununoctium</b><p/>after a day's work<br/>make us something we can use-<br/>well, it's magnetic.<p/><div style='font-size:0.8em'><i>[Just a little too shaky, here- bombarding lead atoms with high-energy krypton ions]</i></div><p/><a href='mailto:snakedoctor@earthlink.net'>loyd myatt</a>";

          return haiku[elementNum];
       }